// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: earthquakes.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAllEarthquakes = `-- name: GetAllEarthquakes :many
SELECT id, magnitude, duration, created_at FROM public."earthquake"
`

func (q *Queries) GetAllEarthquakes(ctx context.Context) ([]Earthquake, error) {
	rows, err := q.db.Query(ctx, getAllEarthquakes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Earthquake
	for rows.Next() {
		var i Earthquake
		if err := rows.Scan(
			&i.ID,
			&i.Magnitude,
			&i.Duration,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllStartEndEarthquakes = `-- name: GetAllStartEndEarthquakes :many
SELECT id, magnitude, duration, created_at FROM public."earthquake"
WHERE created_at >= $1 AND created_at <= $2
`

type GetAllStartEndEarthquakesParams struct {
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

func (q *Queries) GetAllStartEndEarthquakes(ctx context.Context, arg GetAllStartEndEarthquakesParams) ([]Earthquake, error) {
	rows, err := q.db.Query(ctx, getAllStartEndEarthquakes, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Earthquake
	for rows.Next() {
		var i Earthquake
		if err := rows.Scan(
			&i.ID,
			&i.Magnitude,
			&i.Duration,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
