// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	GetAllEarthquakes(ctx context.Context) ([]Earthquake, error)
	GetAllReadings(ctx context.Context) ([]Reading, error)
	GetAllStartEndEarthquakes(ctx context.Context, arg GetAllStartEndEarthquakesParams) ([]Earthquake, error)
	GetAllStartEndReadings(ctx context.Context, arg GetAllStartEndReadingsParams) ([]Reading, error)
	GetBatteryLevel(ctx context.Context) (GetBatteryLevelRow, error)
	GetFirstDataDate(ctx context.Context) (pgtype.Timestamptz, error)
	GetTokenByTokenType(ctx context.Context, type_ string) (Token, error)
	GetUserByEmailAndOauthId(ctx context.Context, arg GetUserByEmailAndOauthIdParams) (User, error)
}

var _ Querier = (*Queries)(nil)
