// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: readings.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAllReadings = `-- name: GetAllReadings :many
SELECT id, si_average, si_minimum, si_maximum, battery, signal_strength, created_at FROM public."reading"
`

func (q *Queries) GetAllReadings(ctx context.Context) ([]Reading, error) {
	rows, err := q.db.Query(ctx, getAllReadings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reading
	for rows.Next() {
		var i Reading
		if err := rows.Scan(
			&i.ID,
			&i.SiAverage,
			&i.SiMinimum,
			&i.SiMaximum,
			&i.Battery,
			&i.SignalStrength,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllStartEndReadings = `-- name: GetAllStartEndReadings :many
SELECT id, si_average, si_minimum, si_maximum, battery, signal_strength, created_at FROM public."reading"
WHERE created_at >= $1 AND created_at <= $2
`

type GetAllStartEndReadingsParams struct {
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

func (q *Queries) GetAllStartEndReadings(ctx context.Context, arg GetAllStartEndReadingsParams) ([]Reading, error) {
	rows, err := q.db.Query(ctx, getAllStartEndReadings, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reading
	for rows.Next() {
		var i Reading
		if err := rows.Scan(
			&i.ID,
			&i.SiAverage,
			&i.SiMinimum,
			&i.SiMaximum,
			&i.Battery,
			&i.SignalStrength,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBatteryLevel = `-- name: GetBatteryLevel :one
SELECT battery, created_at FROM public."reading"
ORDER BY created_at DESC
LIMIT 1
`

type GetBatteryLevelRow struct {
	Battery   float64            `json:"battery"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetBatteryLevel(ctx context.Context) (GetBatteryLevelRow, error) {
	row := q.db.QueryRow(ctx, getBatteryLevel)
	var i GetBatteryLevelRow
	err := row.Scan(&i.Battery, &i.CreatedAt)
	return i, err
}

const getFirstDataDate = `-- name: GetFirstDataDate :one
SELECT created_at AS first_date FROM public."reading"
ORDER BY created_at ASC
LIMIT 1
`

func (q *Queries) GetFirstDataDate(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getFirstDataDate)
	var first_date pgtype.Timestamptz
	err := row.Scan(&first_date)
	return first_date, err
}
