// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tokens.sql

package postgres

import (
	"context"
)

const getTokenByTokenType = `-- name: GetTokenByTokenType :one
SELECT id, type, token, created_at, expires_at FROM public."token"
WHERE type = $1
`

func (q *Queries) GetTokenByTokenType(ctx context.Context, type_ string) (Token, error) {
	row := q.db.QueryRow(ctx, getTokenByTokenType, type_)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Token,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
