// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package postgres

import (
	"context"
)

const getUserByEmailAndOauthId = `-- name: GetUserByEmailAndOauthId :one
SELECT id, oauth_id, name, email, phone_number, role, profile_image, is_in_school, expo_push_token, web_push_subscription, alert_notification, push_notification, sms_notification, created_at FROM public."user"
WHERE email = $1 AND oauth_id = $2
`

type GetUserByEmailAndOauthIdParams struct {
	Email   string `json:"email"`
	OauthID string `json:"oauth_id"`
}

func (q *Queries) GetUserByEmailAndOauthId(ctx context.Context, arg GetUserByEmailAndOauthIdParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmailAndOauthId, arg.Email, arg.OauthID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OauthID,
		&i.Name,
		&i.Email,
		&i.PhoneNumber,
		&i.Role,
		&i.ProfileImage,
		&i.IsInSchool,
		&i.ExpoPushToken,
		&i.WebPushSubscription,
		&i.AlertNotification,
		&i.PushNotification,
		&i.SmsNotification,
		&i.CreatedAt,
	)
	return i, err
}
